### ISSUE TITLE
Raspberry Pi Zero 2 W 対応

### ISSUE THREAD

**Issue by kou029w** [chirimen-oh/chirimen-lite#2]
(日本においては技適未取得なので将来) Raspberry Pi Zero 2 W に対応する。
もし仮に従来のRaspberry Pi Zeroへのサポートを打ち切るならば、おそらくNodeSourceの公式のバイナリーがサポートしているので非公式ビルドを使わなくてよくなると思う。

https://github.com/chirimen-oh/chirimen-lite/tree/master/stage2/99-install-nodejs これをNodeSourceからのインストールに変更。

**Comment by satakagi** [comment]
起動直後　wlan0が見えてないようです
pi@raspberrypi:~$  sudo iwlist wlan0 scan
wlan0     Interface doesn't support scanning : Network is down

**Comment by kou029w** [comment]
rfkillが働いているみたいですね。最新版に更新してWi-Fi国セットアップ用のコードを加えてみました。30分後にReleasesにv0.2.0として加わる予定。これで試してもらって難しいようなら、イメージのビルドプロセスを見直すか、CHIRIMEN setupなどかどこかでrfkillを無効化するなど必要かもです。

**Comment by kou029w** [comment]
https://github.com/chirimen-oh/chirimen-lite/releases/tag/v0.2.2 こちらが最新版になります。

**Comment by kou029w** [comment]
> satakagi 16:24 新しいCHIRIMEN Liteイメージ(0.2.2)でZero2Wの動作確認しました。新しいイメージでは、初期ブート後、wifiは有効化された状態になっていると思います。

(Slackより)

> もし仮に従来のRaspberry Pi Zeroへのサポートを打ち切るならば、おそらくNodeSourceの公式のバイナリーがサポートしているので非公式ビルドを使わなくてよくなると思う。

これは無し。

**Comment by satakagi** [comment]
基本的な動作確認（チュートリアル通し＆カメラ）完了しました。　公式に対応ということで良いと思います！
